server:
  port: 8080
  servlet:
    context-path: /google-login

spring:
  application:
    name: google-login
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

jwt:
  key: ${JWT_KEY}
  expiration-time: 3600 #seconds
  refreshExpiration-time: 604800 #seconds

openapi: 3.0.4
# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

# 2) Apply the security globally to all operations
security:
  - bearerAuth: [] # use the same name as above